dist: trusty
sudo: true

language: node_js
node_js:
  - '12'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable
    update: true

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox