dist: trusty
sudo: false

language: node_js
node_js:
  - '12'

addons:
  update: true
  chrome: stable
  apt:
    sources:
      - google-chrome
    packages:
      - dpkg
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox